# set base image (host OS)
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-build
#FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-buster-build

# set the working directory in the container
WORKDIR /code

# install dependencies
RUN pip install RPi.GPIO --no-cache-dir
RUN pip install requests

# copy the content of the local src directory to the working directory
COPY SafeShutdown.py .

# command to run on container start
ENTRYPOINT ["python", "SafeShutdown.py"]